fail_fast: true
default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: local
    hooks:
      - id: format
        name: Formats the package using ruff, toml-sort, and black.
        entry: poetry run poe format
        language: system
        types: [python]
        pass_filenames: false
        stages: [push]

  - repo: local
    hooks:
      - id: export-dependencies
        name: Exports package dependencies by groups.
        entry: poetry run poe export-dependencies
        language: system
        types: [python]
        pass_filenames: false
        stages: [push]
