fail_fast: true
repos:
  - repo: local
    hooks:
      - id: format
        name: Formats the package using ruff, docformatter, toml-sort, and black.
        entry: poetry run poe format
        language: system
        types: [python]
        stages: [push]
        pass_filenames: false

  - repo: local
    hooks:
      - id: export-dependencies
        name: Exports package dependencies by groups.
        entry: poetry run poe export-dependencies
        language: system
        types: [python]
        stages: [push]
        pass_filenames: false
