fail_fast: true
repos:
  - repo: local
    hooks:
      - id: export-dependencies
        name: Exports the package dependencies by groups.
        entry: poetry run poe export-dependencies
        language: system
        types: [python]
        stages: [push]
        pass_filenames: false

  - repo: local
    hooks:
      - id: toml-sort
        name: toml-sort
        entry: poetry run toml-sort
        language: system
        types: [python]
        files: pyproject.toml

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: docformatter
        name: docformatter
        entry: poetry run docformatter
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
