fail_fast: true
repos:
  - repo: local
    hooks:
      - id: format
        name: Formats the package using ruff, docformatter, toml-sort, and black.
        entry: poetry run poe format
        language: system
        types: [python]
        pass_filenames: false
