coverage:
  status:
    project:
      default:
        target: auto
        threshold: "0%"
        base: auto
        if_not_found: success
        informational: true
        only_pulls: false

    patch:
      default:
        informational: true
