site_name: SeSG
repo_url: https://github.com/demetrius-mp/sesg
repo_name: demetrius-mp/sesg
edit_uri: tree/main/docs

theme:
  name: material

markdown_extensions:
- attr_list

extra_css:
- stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]