site_name: SeSG
repo_url: https://github.com/demetrius-mp/sesg-package
repo_name: demetrius-mp/sesg-package
edit_uri: tree/main/docs

watch:
  - src
  - docs

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - Code Reference: reference/

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
