name: Pipeline
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      
      - name: Install poetry
        run: pipx install poetry
      
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      
      - name: Install dependencies
        run: poetry install --without doc,local
      
      - name: Lints and formats the package
        run: poetry run poe format

      - name: Run tests
        run: poetry run poe test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}